import type { RetailCategory, BudgetCategory } from '@foodlovers/types'

export const BUDGET_CATEGORIES: BudgetCategory[] = [
  { id: 'fresh-food', name: 'Fresh Food', color: '#46B39D', iconName: 'leaf' },
  { id: 'pantry-staples', name: 'Pantry Staples', color: '#B8A47C', iconName: 'archive' },
  { id: 'proteins', name: 'Proteins', color: '#C4785C', iconName: 'drumstick-bite' },
  { id: 'beverages', name: 'Beverages', color: '#6B8DAE', iconName: 'coffee' },
  { id: 'snacks-treats', name: 'Snacks & Treats', color: '#C27BA0', iconName: 'cookie' },
  { id: 'household', name: 'Household', color: '#7B9EA8', iconName: 'home' },
  { id: 'personal-care', name: 'Personal Care', color: '#A88DB5', iconName: 'heart' },
  { id: 'baby-kids', name: 'Baby & Kids', color: '#D4A574', iconName: 'baby' },
]

export const RETAIL_CATEGORIES: RetailCategory[] = [
  {
    id: 'dairy-eggs',
    name: 'Dairy & Eggs',
    iconName: 'egg',
    sortOrder: 1,
    defaultBudgetCategoryId: 'fresh-food',
    defaultEssentialityTier: 'ESSENTIAL',
  },
  {
    id: 'bakery',
    name: 'Bakery',
    iconName: 'bread-slice',
    sortOrder: 2,
    defaultBudgetCategoryId: 'fresh-food',
    defaultEssentialityTier: 'ESSENTIAL',
  },
  {
    id: 'fresh-produce',
    name: 'Fresh Produce',
    iconName: 'carrot',
    sortOrder: 3,
    defaultBudgetCategoryId: 'fresh-food',
    defaultEssentialityTier: 'ESSENTIAL',
  },
  {
    id: 'meat-poultry',
    name: 'Meat & Poultry',
    iconName: 'drumstick-bite',
    sortOrder: 4,
    defaultBudgetCategoryId: 'proteins',
    defaultEssentialityTier: 'ESSENTIAL',
  },
  {
    id: 'frozen',
    name: 'Frozen',
    iconName: 'snowflake',
    sortOrder: 5,
    defaultBudgetCategoryId: 'pantry-staples',
    defaultEssentialityTier: 'SEMI_ESSENTIAL',
  },
  {
    id: 'pantry-canned',
    name: 'Pantry & Canned',
    iconName: 'archive',
    sortOrder: 6,
    defaultBudgetCategoryId: 'pantry-staples',
    defaultEssentialityTier: 'ESSENTIAL',
  },
  {
    id: 'beverages',
    name: 'Beverages',
    iconName: 'coffee',
    sortOrder: 7,
    defaultBudgetCategoryId: 'beverages',
    defaultEssentialityTier: 'SEMI_ESSENTIAL',
  },
  {
    id: 'snacks-confectionery',
    name: 'Snacks & Confectionery',
    iconName: 'cookie',
    sortOrder: 8,
    defaultBudgetCategoryId: 'snacks-treats',
    defaultEssentialityTier: 'DISCRETIONARY',
  },
  {
    id: 'breakfast-cereals',
    name: 'Breakfast & Cereals',
    iconName: 'sun',
    sortOrder: 9,
    defaultBudgetCategoryId: 'pantry-staples',
    defaultEssentialityTier: 'SEMI_ESSENTIAL',
  },
  {
    id: 'condiments-sauces',
    name: 'Condiments & Sauces',
    iconName: 'flask',
    sortOrder: 10,
    defaultBudgetCategoryId: 'pantry-staples',
    defaultEssentialityTier: 'SEMI_ESSENTIAL',
  },
  {
    id: 'cleaning-household',
    name: 'Cleaning & Household',
    iconName: 'spray-can',
    sortOrder: 11,
    defaultBudgetCategoryId: 'household',
    defaultEssentialityTier: 'ESSENTIAL',
  },
  {
    id: 'personal-care',
    name: 'Personal Care',
    iconName: 'heart',
    sortOrder: 12,
    defaultBudgetCategoryId: 'personal-care',
    defaultEssentialityTier: 'SEMI_ESSENTIAL',
  },
  {
    id: 'baby',
    name: 'Baby',
    iconName: 'baby',
    sortOrder: 13,
    defaultBudgetCategoryId: 'baby-kids',
    defaultEssentialityTier: 'ESSENTIAL',
  },
]
