import type { Product } from '@foodlovers/types'

/**
 * Realistic SA grocery products. Prices in cents (ZAR).
 * Each product has all three classification layers assigned.
 */
export const PRODUCTS: Product[] = [
  // ── Fresh Food / Dairy ──
  {
    id: 'p-001',
    name: 'Full Cream Milk 2L',
    description: 'Fresh full cream milk',
    imageUrl: '/images/products/milk-2l.jpg',
    price: 3499,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '2L',
    retailCategoryId: 'dairy-eggs',
    budgetCategoryId: 'fresh-food',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-002',
    name: 'Large Eggs 6-pack',
    description: 'Free range large eggs',
    imageUrl: '/images/products/eggs-6.jpg',
    price: 4299,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '6 pack',
    retailCategoryId: 'dairy-eggs',
    budgetCategoryId: 'fresh-food',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-003',
    name: 'Cheddar Cheese 400g',
    description: 'Mature cheddar cheese block',
    imageUrl: '/images/products/cheddar-400g.jpg',
    price: 7999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '400g',
    retailCategoryId: 'dairy-eggs',
    budgetCategoryId: 'fresh-food',
    essentialityTier: 'SEMI_ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── Fresh Food / Bakery ──
  {
    id: 'p-004',
    name: 'White Bread 700g',
    description: 'Sliced white bread',
    imageUrl: '/images/products/white-bread.jpg',
    price: 1699,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '700g',
    retailCategoryId: 'bakery',
    budgetCategoryId: 'fresh-food',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-005',
    name: 'Brown Bread 700g',
    description: 'Sliced brown bread',
    imageUrl: '/images/products/brown-bread.jpg',
    price: 1799,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '700g',
    retailCategoryId: 'bakery',
    budgetCategoryId: 'fresh-food',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── Fresh Produce ──
  {
    id: 'p-006',
    name: 'Bananas 1kg',
    description: 'Fresh ripe bananas',
    imageUrl: '/images/products/bananas.jpg',
    price: 2199,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '1kg',
    retailCategoryId: 'fresh-produce',
    budgetCategoryId: 'fresh-food',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-007',
    name: 'Tomatoes 1kg',
    description: 'Fresh vine tomatoes',
    imageUrl: '/images/products/tomatoes.jpg',
    price: 2999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '1kg',
    retailCategoryId: 'fresh-produce',
    budgetCategoryId: 'fresh-food',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-008',
    name: 'Onions 1kg',
    description: 'Brown onions',
    imageUrl: '/images/products/onions.jpg',
    price: 1899,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '1kg',
    retailCategoryId: 'fresh-produce',
    budgetCategoryId: 'fresh-food',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-009',
    name: 'Potatoes 2kg',
    description: 'Fresh potatoes',
    imageUrl: '/images/products/potatoes.jpg',
    price: 3499,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '2kg',
    retailCategoryId: 'fresh-produce',
    budgetCategoryId: 'fresh-food',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── Proteins / Meat ──
  {
    id: 'p-010',
    name: 'Chicken Breasts 1kg',
    description: 'Fresh skinless chicken breasts',
    imageUrl: '/images/products/chicken-breasts.jpg',
    price: 8999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '1kg',
    retailCategoryId: 'meat-poultry',
    budgetCategoryId: 'proteins',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-011',
    name: 'Beef Mince 500g',
    description: 'Lean beef mince',
    imageUrl: '/images/products/beef-mince.jpg',
    price: 6999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '500g',
    retailCategoryId: 'meat-poultry',
    budgetCategoryId: 'proteins',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-012',
    name: 'Boerewors 500g',
    description: 'Traditional South African sausage',
    imageUrl: '/images/products/boerewors.jpg',
    price: 7499,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '500g',
    retailCategoryId: 'meat-poultry',
    budgetCategoryId: 'proteins',
    essentialityTier: 'SEMI_ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── Pantry Staples ──
  {
    id: 'p-013',
    name: 'White Rice 2kg',
    description: 'Long grain white rice',
    imageUrl: '/images/products/rice-2kg.jpg',
    price: 3999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '2kg',
    retailCategoryId: 'pantry-canned',
    budgetCategoryId: 'pantry-staples',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-014',
    name: 'Cooking Oil 750ml',
    description: 'Sunflower cooking oil',
    imageUrl: '/images/products/cooking-oil.jpg',
    price: 3499,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '750ml',
    retailCategoryId: 'pantry-canned',
    budgetCategoryId: 'pantry-staples',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-015',
    name: 'Tinned Baked Beans 410g',
    description: 'Baked beans in tomato sauce',
    imageUrl: '/images/products/baked-beans.jpg',
    price: 1899,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '410g',
    retailCategoryId: 'pantry-canned',
    budgetCategoryId: 'pantry-staples',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-016',
    name: 'Spaghetti 500g',
    description: 'Durum wheat spaghetti',
    imageUrl: '/images/products/spaghetti.jpg',
    price: 1999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '500g',
    retailCategoryId: 'pantry-canned',
    budgetCategoryId: 'pantry-staples',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-017',
    name: 'Maize Meal 2.5kg',
    description: 'Super maize meal',
    imageUrl: '/images/products/maize-meal.jpg',
    price: 3299,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '2.5kg',
    retailCategoryId: 'pantry-canned',
    budgetCategoryId: 'pantry-staples',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── Beverages ──
  {
    id: 'p-018',
    name: 'Still Water 5L',
    description: 'Natural spring water',
    imageUrl: '/images/products/water-5l.jpg',
    price: 1999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '5L',
    retailCategoryId: 'beverages',
    budgetCategoryId: 'beverages',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-019',
    name: 'Rooibos Tea 40s',
    description: 'South African rooibos tea bags',
    imageUrl: '/images/products/rooibos.jpg',
    price: 2999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '40 bags',
    retailCategoryId: 'beverages',
    budgetCategoryId: 'beverages',
    essentialityTier: 'SEMI_ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-020',
    name: 'Coca-Cola 2L',
    description: 'Coca-Cola original',
    imageUrl: '/images/products/coke-2l.jpg',
    price: 2499,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '2L',
    retailCategoryId: 'beverages',
    budgetCategoryId: 'beverages',
    essentialityTier: 'DISCRETIONARY',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-021',
    name: 'Orange Juice 1L',
    description: '100% fresh orange juice',
    imageUrl: '/images/products/oj-1l.jpg',
    price: 3999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '1L',
    retailCategoryId: 'beverages',
    budgetCategoryId: 'beverages',
    essentialityTier: 'SEMI_ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── Snacks & Treats ──
  {
    id: 'p-022',
    name: 'Lay\'s Chips 125g',
    description: 'Salted potato chips',
    imageUrl: '/images/products/lays.jpg',
    price: 2499,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '125g',
    retailCategoryId: 'snacks-confectionery',
    budgetCategoryId: 'snacks-treats',
    essentialityTier: 'DISCRETIONARY',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-023',
    name: 'Cadbury Dairy Milk 80g',
    description: 'Milk chocolate slab',
    imageUrl: '/images/products/dairy-milk.jpg',
    price: 2999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '80g',
    retailCategoryId: 'snacks-confectionery',
    budgetCategoryId: 'snacks-treats',
    essentialityTier: 'DISCRETIONARY',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-024',
    name: 'Biltong 100g',
    description: 'Traditional beef biltong',
    imageUrl: '/images/products/biltong.jpg',
    price: 5999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '100g',
    retailCategoryId: 'snacks-confectionery',
    budgetCategoryId: 'snacks-treats',
    essentialityTier: 'DISCRETIONARY',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-025',
    name: 'Simba Chips 125g',
    description: 'Mrs Balls Chutney flavour',
    imageUrl: '/images/products/simba.jpg',
    price: 2499,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '125g',
    retailCategoryId: 'snacks-confectionery',
    budgetCategoryId: 'snacks-treats',
    essentialityTier: 'DISCRETIONARY',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── Household ──
  {
    id: 'p-026',
    name: 'Dishwashing Liquid 750ml',
    description: 'Lemon scented dish soap',
    imageUrl: '/images/products/dish-soap.jpg',
    price: 2999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '750ml',
    retailCategoryId: 'cleaning-household',
    budgetCategoryId: 'household',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-027',
    name: 'Toilet Paper 9-pack',
    description: '2-ply toilet paper',
    imageUrl: '/images/products/toilet-paper.jpg',
    price: 8999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '9 rolls',
    retailCategoryId: 'cleaning-household',
    budgetCategoryId: 'household',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-028',
    name: 'Laundry Detergent 2kg',
    description: 'Washing powder for all machines',
    imageUrl: '/images/products/detergent.jpg',
    price: 6999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '2kg',
    retailCategoryId: 'cleaning-household',
    budgetCategoryId: 'household',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── Personal Care ──
  {
    id: 'p-029',
    name: 'Toothpaste 100ml',
    description: 'Fluoride toothpaste',
    imageUrl: '/images/products/toothpaste.jpg',
    price: 3499,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '100ml',
    retailCategoryId: 'personal-care',
    budgetCategoryId: 'personal-care',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-030',
    name: 'Bar Soap 175g',
    description: 'Moisturising body soap',
    imageUrl: '/images/products/soap.jpg',
    price: 1999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '175g',
    retailCategoryId: 'personal-care',
    budgetCategoryId: 'personal-care',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── Breakfast ──
  {
    id: 'p-031',
    name: 'Cornflakes 500g',
    description: 'Toasted corn flakes cereal',
    imageUrl: '/images/products/cornflakes.jpg',
    price: 4499,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '500g',
    retailCategoryId: 'breakfast-cereals',
    budgetCategoryId: 'pantry-staples',
    essentialityTier: 'SEMI_ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-032',
    name: 'Peanut Butter 400g',
    description: 'Smooth peanut butter',
    imageUrl: '/images/products/peanut-butter.jpg',
    price: 4999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '400g',
    retailCategoryId: 'condiments-sauces',
    budgetCategoryId: 'pantry-staples',
    essentialityTier: 'SEMI_ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── Condiments ──
  {
    id: 'p-033',
    name: 'Tomato Sauce 700ml',
    description: 'Classic tomato ketchup',
    imageUrl: '/images/products/tomato-sauce.jpg',
    price: 2999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '700ml',
    retailCategoryId: 'condiments-sauces',
    budgetCategoryId: 'pantry-staples',
    essentialityTier: 'SEMI_ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-034',
    name: 'Mrs Balls Chutney 470g',
    description: 'Original recipe chutney',
    imageUrl: '/images/products/mrs-balls.jpg',
    price: 3999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '470g',
    retailCategoryId: 'condiments-sauces',
    budgetCategoryId: 'pantry-staples',
    essentialityTier: 'SEMI_ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── Frozen ──
  {
    id: 'p-035',
    name: 'Frozen Mixed Veg 1kg',
    description: 'Frozen mixed vegetables',
    imageUrl: '/images/products/frozen-veg.jpg',
    price: 3999,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '1kg',
    retailCategoryId: 'frozen',
    budgetCategoryId: 'fresh-food',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  {
    id: 'p-036',
    name: 'Fish Fingers 400g',
    description: 'Crumbed fish fingers',
    imageUrl: '/images/products/fish-fingers.jpg',
    price: 5499,
    currencyCode: 'ZAR',
    market: 'ZA',
    unit: '400g',
    retailCategoryId: 'frozen',
    budgetCategoryId: 'proteins',
    essentialityTier: 'SEMI_ESSENTIAL',
    inStock: true,
    storeId: 'store-za-01',
  },
  // ── ZW market products ──
  {
    id: 'p-zw-001',
    name: 'Whole Milk 1L',
    description: 'Fresh whole milk',
    imageUrl: '/images/products/milk-zw.jpg',
    price: 250,
    currencyCode: 'USD',
    market: 'ZW',
    unit: '1L',
    retailCategoryId: 'dairy-eggs',
    budgetCategoryId: 'fresh-food',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-zw-01',
  },
  {
    id: 'p-zw-002',
    name: 'Mealie Meal 10kg',
    description: 'Roller meal maize',
    imageUrl: '/images/products/mealie-meal-zw.jpg',
    price: 800,
    currencyCode: 'USD',
    market: 'ZW',
    unit: '10kg',
    retailCategoryId: 'pantry-canned',
    budgetCategoryId: 'pantry-staples',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-zw-01',
  },
  {
    id: 'p-zw-003',
    name: 'Cooking Oil 2L',
    description: 'Refined cooking oil',
    imageUrl: '/images/products/oil-zw.jpg',
    price: 450,
    currencyCode: 'USD',
    market: 'ZW',
    unit: '2L',
    retailCategoryId: 'pantry-canned',
    budgetCategoryId: 'pantry-staples',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-zw-01',
  },
  {
    id: 'p-zw-004',
    name: 'Chicken Pieces 2kg',
    description: 'Fresh chicken pieces',
    imageUrl: '/images/products/chicken-zw.jpg',
    price: 750,
    currencyCode: 'USD',
    market: 'ZW',
    unit: '2kg',
    retailCategoryId: 'meat-poultry',
    budgetCategoryId: 'proteins',
    essentialityTier: 'ESSENTIAL',
    inStock: true,
    storeId: 'store-zw-01',
  },
  {
    id: 'p-zw-005',
    name: 'Mazoe Orange 2L',
    description: 'Orange crush concentrate',
    imageUrl: '/images/products/mazoe.jpg',
    price: 350,
    currencyCode: 'USD',
    market: 'ZW',
    unit: '2L',
    retailCategoryId: 'beverages',
    budgetCategoryId: 'beverages',
    essentialityTier: 'DISCRETIONARY',
    inStock: true,
    storeId: 'store-zw-01',
  },
]
